name: Ubuntu RDP

on:
  workflow_dispatch:
    inputs:
      hostname:
        description: 'Enter Hostname:'
        required: false
        default: ubuntu
        type: string
      username:
        description: 'Enter Username:'
        required: false
        default: user
        type: string
      password:
        description: 'Enter Password:'
        required: false
        default: root
        type: string
      Pin:
        description: 'Enter a Pin (more or equal to 6 digits)'
        required: false
        default: 123456
        type: number
      CRP:
        description: 'Visit at http://remotedesktop.google.com/headless and, copy the command after authentication'
        required: false
        default: 4/0AVMBsJjxAGp5zalxn9FI5y142x3Bvg6DoQ_ObhMlJPgonyPsBQMzEKMc-PEA3gu6L4e8AA
        type: string

env:
  hostname: ${{ inputs.hostname }}
  username: ${{ inputs.username }}
  password: ${{ inputs.password }}
  Pin: ${{ inputs.Pin }}
  CRP: ${{ inputs.CRP }}

jobs:
  build:
    name: Deploy Server
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Cleanup Junk
        run: |
          curl -L -o Cleanup.sh \
              https://raw.githubusercontent.com/dprised/Ubuntu_RDP/refs/heads/main/Cleanup.sh
          chmod +x Cleanup.sh
          ./Cleanup.sh

      - name: Create Server
        run: |
          curl -L -o Ubuntu_RDP.sh \
              https://raw.githubusercontent.com/dprised/Ubuntu_RDP/refs/heads/main/Ubuntu_RDP.sh
          chmod +x Ubuntu_RDP.sh
          ./Ubuntu_RDP.sh

      - name: Keep Running
        run: |
          curl -L -o Keep_Running.sh \
              https://raw.githubusercontent.com/dprised/Ubuntu_RDP/refs/heads/main/Keep_Running.sh
          chmod +x Keep_Running.sh
          ./Keep_Running.sh
